//Convert data properties tolast_invoice_date

export const columnsKey = {
  vendor_name: "Vendor Name",
  total_net_amount: "Total Net Amount",
  total_paid_amount: "Total Paid Amount",
  remaining_amount: "Balance Amount",
  total_invoices: "Total Invoices",
  // average_paid_amount: "Average Paid Amount",
  product_group: "Product Group",
  product_name: "Product Group",
  total_sold_quantity: "Total Sold Quantity",
  invoice_id: "Invoice Id",
  t_year: "Year",
  t_month: "Month",
  total_amount: "Total Amount",
  total_detailed_amount: "Total Detailed Amount",
  running_total_paid: "Running Total Paid",
  product_code: "Product Code",
  warehouse_code: "Warehouse Code",
  warehouse_description: "Warehouse Description",
  in_quantity: "In Quantity",
  out_quantity: "Out Quantity",
  balance_quantity: "Balance Quantity",
  total_sales_amount: "Total Sales Amount",
  // average_sales_amount: "Average Sales Amount",
  description: "Description",
  last_invoice_date: "Last Invoice Date",
  days_since_last_transaction: "Days Since Last Transaction",
  total_in_qty: "Total In Quantity",
  total_out_qty: "Total Out Quantity",
  total_bal_qty: "Total Balance Quantity",
  vendor_type: "Vendor Type",
  transaction_type: "Transaction Type",
  segment: "Segment",
  last_sale_date: "Last Sale Date",
  product_id: "Product Id",
  qty: "Quantity",
  unit_rate: "Unit Rate",
  invoice_date: "Invoice Date",
  StockMovementType: "Stock Movement Type",
  total_receivables: "Total Receivables",
  balance_amount: "Balance Amount",
  tax_amount: "Tax Amount",
  total_tax_amount: "Total Tax Amount",
  total_receivables_amount: "Total Receivables Amount",
  invoice_code: "Invoice Code",
  total_quantity: "Total Quantity",
  sale_date: "Sale Date",
  customer_name: "Customer Name",
  total_invoice: "Total Invoices",
  total_tax: "Total Tax",
  warehouse_id: "Warehouse Id",
  last_change_date: "Last Change Date",
  days_category: "Aging Days",
  bal_qty: "Balance Quantity",
  average_running_amount_by_bal_qty: "Avarage Amount",
  running_amount: "Running Amount",
  running_qty: "Running Quantity",
  amount: "Amount",
  vendor_description: "Vendor Description",
};
export const skipColumns = [
  "vendor_id",
  "id",
  "invoice_detail_id",
  "product_id",
  "product_description",
  "last_change",
  "overtime_sold_quantities",
  "max_sales_amount",
  "min_sales_amount",
  "currency",
  "segment_id",
  "average_paid_amount",
  "average_sales_amount",
];

export const segmentOption = [
  { key: "AT-EQP-KHI", value: "AT-EQP-KHI" },
  { key: "AT-EQP-LHR", value: "AT-EQP-LHR" },
  { key: "AT-EQP-ISL", value: "AT-EQP-ISL" },
  { key: "AT-AM-SRV-KHI", value: "AT-AM-SRV-KHI" },
  { key: "AT-AM-SRV-LHR", value: "AT-AM-SRV-LHR" },
  { key: "AT-AM-SRV-ISL", value: "AT-AM-SRV-ISL" },
  { key: "PMP-EQP-KHI", value: "PMP-EQP-KHI" },
  { key: "PMP-EQP-LHR", value: "PMP-EQP-LHR" },
  { key: "PMP-EQP-ISL", value: "PMP-EQP-ISL" },
  { key: "PMP-SRV-KHI", value: "PMP-SRV-KHI" },
  { key: "PMP-SRV-LHR", value: "PMP-SRV-LHR" },
  { key: "PMP-SRV-ISL", value: "PMP-SRV-ISL" },
  { key: "RIC-EQP-KHI", value: "RIC-EQP-KHI" },
  { key: "RIC-EQP-LHR", value: "RIC-EQP-LHR" },
  { key: "RIC-SRV-KHI", value: "RIC-SRV-KHI" },
  { key: "RIC-SRV-LHR", value: "RIC-SRV-LHR" },
  { key: "ABB-KHI", value: "ABB-KHI" },
  { key: "ABB-LHR", value: "ABB-LHR" },
  { key: "ABB-ISL", value: "ABB-ISL" },
  { key: "CHT-KHI", value: "CHT-KHI" },
  { key: "CHT-LHR", value: "CHT-LHR" },
  { key: "CHT-ISL", value: "CHT-ISL" },
  { key: "GE-KHI", value: "GE-KHI" },
  { key: "GE-LHR", value: "GE-LHR" },
  { key: "GE-ISL", value: "GE-ISL" },
  { key: "ABB-RTL", value: "ABB-RTL" },
];

export const amountField = [
  "total_net_amount",
  "total_paid_amount",
  "total_detailed_amount",
  "remaining_amount",
  "average_paid_amount",
  "total_amount",
  "running_total_paid",
  "total_sales_amount",
  "average_sales_amount",
  "total_receivables",
  "total_receivables_amount",
  "total_tax",
  "total_tax_amount",
  "tax_amount",
  "balance_amount",
  "amount",
  // "running_qty",
  "running_amount",
  "average_running_amount_by_bal_qty",
  // "bal_qty"
];
export const dateField = [
  "last_invoice_date",
  "last_sale_date",
  "invoice_date",
  "sale_date",
  "last_change_date",
];

export const searchFieldHelepers = [
  "vendor_name",
  "product_name",
  "segment",
  "product_group",
  "description",
  "warehouse_description",
  "invoice_id",
  "invoice_code",
  "customer_name",
  "vendor_description",
];

export const infinitTable = [
  "sales",
  "stock-aging",
  "warehouse-sale",
  "receivables-with-start-end-date",
  "invoice-sales",
  "top-selling-products",
  "sales-summary",
  "customer",
  "Vendor Summary",
  "Product Summary",
  "receivables-with-filter",
];
